name: wave
channels:
  - pytorch-nightly
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - pytorch=2.1.0.dev20230318
  - pytorch-lightning=2.0.0
  - numpy=1.23.5
  - ffmpeg=5.1.2
  - gdown=4.6.4
  - hydra-core=1.3.2
  - ipykernel=6.19.2
  - ipython=8.10.0
  - ipywidgets=8.0.4
  - jupyterlab=3.5.3
  - librosa=0.9.2
  - libsndfile=1.0.31
  - libsqlite=3.40.0
  - matplotlib=3.6.2
  - notebook=6.5.2
  - numba=0.56.4
  - omegaconf=2.3.0
  - onnx=1.13.0
  - onnxruntime=1.13.1
  - pandas=1.5.2
  - pip=23.0.1
  - progressbar=2.5
  - pysoundfile=0.11.0
  - pytest=7.1.2
  - python=3.9.16
  - scikit-learn=1.2.1
  - scipy=1.10.0
  - seaborn=0.12.2
  - setuptools=65.6.3
  - sqlite=3.41.1
  - tqdm=4.64.1
  - pip:
      - archisound==0.0.6
      - audio-diffusion-pytorch==0.1.3
      - audio-encoders-pytorch==0.0.22
      - audiomentations==0.28.0
      - auraloss==0.3.0
      - huggingface-hub==0.13.1
      - lightning==2.0.0
      - lightning-cloud==0.5.31
      - mlflow==2.2.2
      - pyloudnorm==0.1.1
      - simpleaudio==1.0.4
      - torch==2.0.0
      - torch-audiomentations==0.11.0
      - torchaudio==2.0.0
      - torchvision==0.15.0
      - transformers==4.26.1
