batch_size: 64
learning_rate: 0.0003
max_epochs: 1000
check_val_every_n_epoch: 10
accelerator: mps # "cpu", "gpu", "tpu", "ipu", "auto"
continue_test: true

lossfn: 'DC_SDSDR_SNR_Loss' # error_to_signal, ESRLoss, DCLoss, LogCoshLoss, SNRLoss, SDSDRLoss, MSELoss, DC_SDSDR_SNR_Loss
loss_preemphasis_filter: false
loss_preemphasis_coeff: 0.95

experiment_name: 'wavenet_DC_SDSDR_SNR_Loss'

resume_checkpoint: false
checkpoint_file: './outputs/2023-03-02/05-59-33/models/wavenet.ckpt'

use_checkpoint_callback: true
model_checkpoint_path: './models/'

use_mlflow: true
tracking_uri: './mlruns'