defaults:
  - loss: mr_loss_small

batch_size: 64
learning_rate: 0.0003
max_epochs: 1
check_val_every_n_epoch: 10
accelerator: mps # "cpu", "gpu", "tpu", "ipu", "auto"
num_workers: 6 # number of workers for training dataloader
continue_test: true

lossfn: 'DC_SDSDR_SNR_Loss' # error_to_signal, ESRLoss, DCLoss, LogCoshLoss, SNRLoss, SDSDRLoss, MSELoss, DC_SDSDR_SNR_Loss, STFTLoss, MelSTFTLoss, MultiResolutionSTFTLoss, RandomResolutionSTFTLoss
loss_preemphasis_hp_filter: false
loss_preemphasis_hp_coeff: 0.95
loss_preemphasis_aw_filter: false


experiment_name: 'waveunet_DC_SDSDR_SNR_Loss_4096blk'


resume_checkpoint: false
checkpoint_file: './outputs/2023-03-07/13-31-27/models/wavenet_aug_MultiResolutionSTFTLoss epoch=589.ckpt'

use_checkpoint_callback: true
model_checkpoint_path: './models/'

use_mlflow: true
tracking_uri: './mlruns'